# -*- encoding: utf-8 -*-
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl)

# BASED ON VERSION 0.07 (10.0)
{
    "name" : "Poland - Accounting",
    "version" : "1.02 (14.0)",
    "author" : "Cirrus, OpenGLOBE and Grzegorz Grzelak, Bartosz Baranowski, Jan Dziurzyński, Mariusz Osak",
    'license': 'AGPL-3',
    "website": "http://www.openglobe.pl",
    "category" : "Localisation/Country specific stuff",
    'summary': 'The module to manage Polish specific accounting functionality.',
    'depends' : ['sale','account', 'web', 'account_pl_declaration_data', 'account_invoice_pl_og'],
    'data': [
        'data/data.xml',
        'security/ir.model.access.csv',
        'data/account_report.xml',
        'data/assets.xml',
        'data/tax_markers_data.xml',
        'views/account_view.xml',
        'views/product_view.xml',
        'views/report_invoice_register.xml',
        'views/report_jpk_vat_3.xml',
        'views/report_jpk_vat_2020.xml',
        'views/report_vat_7_18.xml',
        'views/report_vat_7_19.xml',
        'views/report_vat_7_20.xml',
        'views/report_vat_7k_12.xml',
        'views/report_vat_7k_13.xml',
        'views/report_vat_7k_14.xml',
        'views/report_vat_ue_4.xml',
        'views/report_trial_balance.xml',
        'views/res_config_settings_view.xml',
        'views/wizard_invoice_register.xml',
        'views/wizard_jpk_wb_view.xml',
        'views/wizard_jpk_fa_1_view.xml',
        'views/wizard_jpk_fa_2_view.xml',
        'views/wizard_jpk_fa_3_view.xml',
        'views/wizard_jpk_vat_3_view.xml',
        'views/wizard_vat_7_18_view.xml',
        'views/wizard_vat_7_19_view.xml',
        'views/wizard_vat_7_20_view.xml',
        'views/wizard_vat_ue_4.xml',
        'views/wizard_trial_balance_view.xml',
        'views/wizard_jpk_vat_2020_view.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
